### ISSUE TITLE
npm start以后访问不到

### ISSUE THREAD

**Issue by elva2596** [akira-cn/handlock#1]
npm start以后在浏览器访问http://localhost:8080/什么都没有

**Comment by akira-cn** [comment]
npm install 都正常吗？如果没有问题的话试试 http://localhost:8080/locker.html 能访问不

**Comment by akira-cn** [comment]
另外如果你的node不是6.x是4.x或更老的版本，你把 webpack.config.js 改一下呗，那里面用了一个函数默认参数的写法要 ES6 才支持，而那个脚本我没有用 babel 编译

```js
module.exports = function(env = {}){
...
```

改成

```js
module.exports = function(env){
    env = env || {};
...
```

**Comment by elva2596** [comment]
Error occured while trying to proxy to: localhost:8080/locker.html 
npm install 没有问题，并且Node版本是6.x
